-- -- -- -- CREATE TABLE streaming(
-- -- -- --     id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
-- -- -- --     nome VARCHAR (50) NOT NULL,
-- -- -- --     duração INT NOT NULL,
-- -- -- --     nota INT NOT NULL
-- -- -- -- -- );

-- -- -- INSERT INTO streaming(nome, duração, nota)
-- -- -- VALUES 
-- -- -- ('Stranger Things','2718','9'),
-- -- -- ('Outer Banks','2000','8'),
-- -- -- ('As Branquelas','109','6'),
-- -- -- ('Coraline e o Mundo Secreto','100','9'),
-- -- -- ('Avatar','162','8'),
-- -- -- ('Avatar 2','192','8'),
-- -- -- ('Avatar 3','195','7'),
-- -- -- ('Para Todos os Garotos que Já Amei','99','10'),
-- -- -- ('Para Todos os Garotos: P.S. Ainda Amo Você','101','7'),
-- -- -- ('Para Todos os Garotos: Para Sempre','116','8'),
-- -- -- ('10 Coisas que Eu Odeio em Você','97','7'),
-- -- -- ('Como Perder um Homem em 10 Dias','116','5'),
-- -- -- ('Enrolados','100','9'),
-- -- -- ('A Princesa e o Sapo','97','9'),
-- -- -- ('A Bela Adormecida','75','9'),
-- -- -- ('A Bela e a Fera','129','7'),
-- -- -- ('Branca de Neve e os Sete Anões','83','10'),
-- -- -- ('Cinderela','105','8'),
-- -- -- ('Moana','107','10'),
-- -- -- ('Moana 2','100','7'),
-- -- -- ('Valente','93','8'),
-- -- -- ('A Pequena Sereia','84','9'),
-- -- -- ('Mulan','87','9'),
-- -- -- ('Pocahontas','81','6'),
-- -- -- ('Descendentes','112','9'),
-- -- -- ('Descendentes 2','111','8'),
-- -- -- ('Descendentes 3','106','8'),
-- -- -- ('Maze Runner: Correr ou Morrer','113','7'),
-- -- -- ('Maze Runner: Prova de Fogo','131','6'),
-- -- -- ('Maze Runner: A Cura Mortal','143','6');

-- -- SELECT * FROM streaming;

-- SELECT nome FROM streaming;
-- -- SELECT nota FROM streaming;a